# Generated by Django 3.2.9 on 2022-01-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
