# Generated by Django 4.0.1 on 2022-02-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_statistics', 'View extra data')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
